### PR TITLE
Add Windows installer rule, start mac installer rule, add ALS installer rules

### PR DESCRIPTION
**Pull request by tynanford**
Hi Han, sorry this is a lot. We can chat if you need more details.

- Added ca addr list variables for both phoebus and alarm server settings files
- Added a check to make distclean rules, i.e. it prompts the user to say yes before removing directory
- Added rules to build phoebus for windows based on this: https://github.com/controlSystemStudio/phoebus#cross-platform-build . make windows will build phoebus for Windows, extract the necessary product files, put them in a directory, and then zip that directory and place the zip files in $(TOP)
- Added rules to build phoebus for Mac similiar to Windows. This is still a work in progress, will be testing soon when I meet with a co-worker with a Mac
- Added rules for ALS phoebus builds. These rules are what I have been using the past few weeks to create our .exe windows installers

Let me know if you have questions

### CODE REVIEW

**Comment by jeonghanlee** [comment]
I am wondering the license of the window binary files (dll, and exe). I assume this is the open source. If you have any license file, please add them into here also.

**Comment by jeonghanlee** [comment]
The maven version for window is 3.6.0. Do you try to do this with the latest version such as 3.6.3?

**Comment by jeonghanlee** [comment]
I don't have time to integrate them (windows, and mac build) in github action yet. Sorry about it.

**Comment by tynanford** [comment]
Oh I see, I used maven version 3.6.1 on my local machine. Before I was compiling on Windows with 3.6.0. 

I actually don't know where the .exe files are from, Mirek provided them. I can delete them from this since we don't know the licensing, and they are not needed for phoebus installation.

**Comment by jeonghanlee** [comment]
Please check them and add them later into if they are open source. If not, we can discuss what we can do in a meeting.

**Pull request merged**
